name: panel_usuario
description: Microservicio en Flutter para el panel de usuario con conexión REST y MongoDB
publish_to: 'none' # Indicates that this is a private project, not published to pub.dev

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3
  provider: ^6.1.3
  flutter_localizations:
    sdk: flutter
  json_annotation: ^4.3.0
  mongo_dart: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true

  assets:
    - assets/images/
